language: node_js
node_js:
  - '0.12'
notifications:
  email: false
before_script:
  - sudo ./bin/build-php7.sh
  - php -v
after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js