language: node_js
node_js:
  - '0.10'
  - '0.11'
notifications:
  email: false
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5-cli
after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js